site_name: GSPKit

theme:
  name: "material"
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.indexes
    - toc.follow

plugins:
- search
- mkdocstrings:
    handlers: 
      python:
        options:
          docstring_style: numpy
          heading_level: 3

nav:
  - Home: index.md
  - API:
    - API: api/index.md
    - Data: api/data.md